version: '3.8'

services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://davidshch:password@db:5432/macromind
    depends_on:
      - db
    volumes:
      - ./backend:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=davidshch
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=macromind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
