"""add_sector_fundamentals_table"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d4b0309cc3'
down_revision: Union[str, None] = 'e4901a03c7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure only this migration creates the sector_fundamentals table and indexes
    # op.create_table('sector_fundamentals',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('sector_name', sa.String(), nullable=True),
    #     sa.Column('date', sa.Date(), nullable=True),
    #     sa.Column('pe_ratio', sa.Float(), nullable=True),
    #     sa.Column('pb_ratio', sa.Float(), nullable=True),
    #     sa.Column('earnings_growth', sa.Float(), nullable=True),
    #     sa.Column('timestamp', sa.DateTime(), nullable=True),
    #     sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_sector_fundamentals_id'), 'sector_fundamentals', ['id'], unique=False)
    # op.create_index(op.f('ix_sector_fundamentals_sector_name'), 'sector_fundamentals', ['sector_name'], unique=False)
    # op.create_index(op.f('ix_sector_fundamentals_date'), 'sector_fundamentals', ['date'], unique=False)
    # op.create_index('idx_sector_date', 'sector_fundamentals', ['sector_name', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_sector_date', table_name='sector_fundamentals')
    # op.drop_index(op.f('ix_sector_fundamentals_date'), table_name='sector_fundamentals')
    # op.drop_index(op.f('ix_sector_fundamentals_sector_name'), table_name='sector_fundamentals')
    # op.drop_index(op.f('ix_sector_fundamentals_id'), table_name='sector_fundamentals')
    # op.drop_table('sector_fundamentals')
    # ### end Alembic commands ###
